service-a:
  image:
    repository: service-a
    tag: latest
  service:
    type: ClusterIP
    port: 8011

service-b:
  image:
    repository: service-b
    tag: latest
  service:
    type: ClusterIP
    port: 8012
  serviceA:
    url: http://service-a:8011
