# Hadolint configuration for Dockerfile security linting
# This configuration balances security best practices with practical considerations

# Rules to ignore (with justification)
ignored:
  # DL3008: Pin versions in apt get install
  # Justification: ca-certificates is a system package that should use the latest available
  # for security updates. Pinning system packages can prevent security updates.
  - DL3008

# Rules to enforce as errors (fail the build)
failure-threshold: error

# Rules to treat as warnings
warning-threshold: warning

# Trusted registries for base images
trustedRegistries:
  - docker.io
  - gcr.io
  - quay.io
  - ghcr.io

# Override specific rules
override:
  # Allow specific base images
  DL3006: false  # Always tag the version of an image explicitly

  # Require specific practices
  DL3009: true   # Delete the apt-get lists after installing something
  DL3015: true   # Avoid additional packages by specifying `--no-install-recommends`
  DL3025: true   # Use arguments JSON notation for CMD and ENTRYPOINT arguments
