name: CI/CD Pipeline - KinD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        service:
          - id: service_a
            name: service-a
            path: ./service_a
          - id: service_b
            name: service-b
            path: ./service_b
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4

    - name: Docker Meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ghcr.io/${{ github.repository_owner }}/${{ matrix.service.name }}
        tags: |
          type=sha,format=long
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.MY_GITHUB_TOKEN }}

    - name: Build Service Image
      uses: docker/build-push-action@v6
      with:
        push: true
        context: ${{ matrix.service.path }}
        tags: ${{ steps.meta.outputs.tags }}

  local-deploy:
    needs: build
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.MY_GITHUB_TOKEN }}

    - name: Pull Docker Images
      run: |
        docker pull ghcr.io/${{ github.repository_owner }}/service-a:sha-${{ github.sha }}
        docker pull ghcr.io/${{ github.repository_owner }}/service-b:sha-${{ github.sha }}
        docker images

    - name: Set up Kubernetes (KinD)
      uses: engineerd/setup-kind@v0.6.2
      with:
        version: "v0.24.0"

    - name: Load images into KinD
      run: |
        kind load docker-image ghcr.io/${{ github.repository_owner }}/service-a:sha-${{ github.sha }}
        kind load docker-image ghcr.io/${{ github.repository_owner }}/service-b:sha-${{ github.sha }}

    - name: Install Helm
      uses: azure/setup-helm@v4
      with:
        version: 'latest'

    - name: Deploy with Helm
      run: |
        helm upgrade --install my-app ./charts/my-app \
          --set service-a.image.repository=ghcr.io/${{ github.repository_owner }}/service-a \
          --set service-b.image.repository=ghcr.io/${{ github.repository_owner }}/service-b \
          --set service-a.image.tag=sha-${{ github.sha }} \
          --set service-b.image.tag=sha-${{ github.sha }} \
          --set service-b.serviceA.url=http://my-app-service-a:8011

    - name: Test Services
      run: |
        kubectl wait --for=condition=ready pod -l app.kubernetes.io/name=service-a --timeout=60s
        kubectl wait --for=condition=ready pod -l app.kubernetes.io/name=service-b --timeout=60s
        kubectl port-forward svc/my-app-service-b 8012:8012 &
        sleep 5
        curl -s http://0.0.0.0:8012/ping_service_a | grep "Greetings from Service A"
