name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  # pull_request:
  #   branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Service A
      uses: docker/build-push-action@v6
      with:
        context: ./service_a
        push: false
        load: true
        tags: service-a:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Build Service B
      uses: docker/build-push-action@v6
      with:
        context: ./service_b
        push: false
        load: true
        tags: service-b:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Set up Kubernetes (KinD)
      uses: engineerd/setup-kind@v0.6.2
      with:
        version: "v0.24.0"

    - name: Load images into KinD
      run: |
        kind load docker-image service-a:latest
        kind load docker-image service-b:latest

    - name: Install Helm
      uses: azure/setup-helm@v3
      with:
        version: 'latest'

    - name: Deploy with Helm
      run: |
        helm install microservices ./helm/microservices

    - name: Test Services
      run: |
        kubectl port-forward svc/service-b 8012:8012 &
        sleep 10
        curl -s http://localhost:8012/call-service-a | grep "Greetings from Service A"
